// Augments the OpenNext-provided global `CloudflareEnv` with this project's
// Worker bindings, vars, and secrets so `getCloudflareContext().env` is typed.
// (Normally generated by `wrangler types` / `opennextjs-cloudflare typegen`;
// kept hand-maintained here to avoid a generated-file step in the toolchain.)
declare global {
  interface CloudflareEnv {
    // Hyperdrive binding (wrangler.toml [[hyperdrive]]). Only `connectionString`
    // is consumed by getDb(); the real binding carries more.
    HYPERDRIVE: { connectionString: string };
    // Better Auth secret (Workers secret) + base URL (var/secret).
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL?: string;
    // Public Supabase config (wrangler.toml [vars]).
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
    // Resend transport (S-11, FR-018 + FR-001's password-reset email). BOTH are
    // Workers *secrets*, not vars — RESEND_FROM_ADDRESS is not sensitive, but
    // plain vars resolve to null in getCloudflareContext().env on this OpenNext
    // version, and a null sender fails every send with a 422.
    RESEND_API_KEY?: string;
    RESEND_FROM_ADDRESS?: string;
    // Svix signing secret for the Resend bounce/complaint webhook (S-12). Also a
    // Workers *secret* — this one genuinely is sensitive: it is the ONLY thing
    // authenticating `/api/webhooks/resend`, so anyone holding it can turn off
    // any owner's daily recap.
    RESEND_WEBHOOK_SECRET?: string;
  }
}

export {};
