// Augments the OpenNext-provided global `CloudflareEnv` with this project's
// Worker bindings, vars, and secrets so `getCloudflareContext().env` is typed.
// (Normally generated by `wrangler types` / `opennextjs-cloudflare typegen`;
// kept hand-maintained here to avoid a generated-file step in the toolchain.)
declare global {
  interface CloudflareEnv {
    // Hyperdrive binding (wrangler.toml [[hyperdrive]]). Only `connectionString`
    // is consumed by getDb(); the real binding carries more.
    HYPERDRIVE: { connectionString: string };
    // Better Auth secret (Workers secret) + base URL (var/secret).
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL?: string;
    // Public Supabase config (wrangler.toml [vars]).
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  }
}

export {};
