name = "sprintflow"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[build]
command = "npm run build:cf"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "86417a117a96464e947d5005e56f2a21"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://uzqwuikgbbkpnemcnlwo.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_lwIhY8exodoHZM-0SjRQEg_6XHX3It-"
